In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')
# 汉化字体
import matplotlib

matplotlib.rc("font", family='DengXian')
%matplotlib inline

In [8]:
a = np.array([[1, 1, 2], [2, 1, 3]])
print(a ** 2)

[[1 1 4]
 [4 1 9]]


In [18]:
print(np.logspace(1, 10, 10, base = 2))
print(np.eye(3))

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
print(np.random.random(5)) # 无约束随机值
print(np.random.rand(3, 4)) #均匀分布

[0.12170319 0.79554487 0.38126942 0.55311609 0.89902373]
[[0.65466487 0.15685035 0.78732565 0.20349682]
 [0.87549952 0.31317385 0.14424446 0.14174676]
 [0.85020027 0.93780302 0.13839086 0.19044355]]


In [21]:
arr = np.array([1, 3, 5])
index = arr > 2
print(arr[index])

[3 5]
